---
title: "About"
---

I am a current second year master of science (ScM) student studying infectious disease epidemiology at the Johns Hopkins Bloomberg School of Public Health. I previously received a BA in Government with a focus on international relations from Cornell University. While in undergrad, I competed on the Cornell University Sailing Team from 2012 to 2016.  

I am interested in infectious disease modelling and its applications in the fight against vaccine preventable diseases. I am specifically interested in researching influenza viruses and their pandemic potential. 

I am currently working for the JHU Department of Epidemiology on a COVID-19, Cholera, and Hepatitis E serologic survey of Chittagong Bangladesh. This work is associated with my masters thesis, focused on exploring Cholera related healthcare seeking in the study cohort. I also work at the JHU's International Vaccine Access Center on several projects related to COVID-19 modeling and COVID-19 vaccine health systems. I have previously volunteered over 200 hrs in clinical settings, interned at the WHO, and worked in project management on the construction of a 50 story skyscraper. 